export const events = [
  {
    date: "2026-01-01",
    title: "Año nuevo",
    category: "festivo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-01-06",
    title: "Día de Reyes",
    category: "festivo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-02-14",
    title: "San Valentín",
    category: "personal",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-03-20",
    title: "Inicio primavera",
    category: "otros",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-04-02",
    title: "Jueves Santo",
    category: "festivo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-04-03",
    title: "Viernes Santo",
    category: "festivo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-05-01",
    title: "Día del trabajo",
    category: "festivo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-05-04",
    title: "Reunión de equipo",
    category: "trabajo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-06-21",
    title: "Solsticio de verano",
    category: "otros",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-07-20",
    title: "Independencia Colombia",
    category: "festivo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-08-07",
    title: "Batalla de Boyacá",
    category: "festivo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-09-15",
    title: "Entrega proyecto",
    category: "trabajo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-10-12",
    title: "Día de la raza",
    category: "festivo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-12-08",
    title: "Inmaculada Concepción",
    category: "festivo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
  {
    date: "2026-12-25",
    title: "Navidad",
    category: "festivo",
    duration: "Todo el día",
    place: "Salón de eventos",
    asistants: "Todo el colegio",
    description:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. ",
    color: "#cbd5e1",
  },
];